version: '3.7'

services:
  mysql:
    container_name: pokemon-mysql
    image: pokemon-mysql
    build:
      context: .
      dockerfile: ./Dockerfile.mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: pokemon
    networks:
      - pokemon-network
    ports:
      - 3306:3306
  app:
    depends_on:
      - mysql
    container_name: pokemon-app
    image: pokemon-app
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    networks:
      - pokemon-network

networks:
  pokemon-network: